"""Pydantic request/response models (the API contract)."""

from app.schemas.action_items import ActionItemCreate, ActionItemOut, ActionItemUpdate, ActionItemWithMeeting
from app.schemas.common import ORMModel, Page
from app.schemas.meetings import (
    MeetingCreate,
    MeetingDetail,
    MeetingListItem,
    MeetingUpdate,
    ParticipantIn,
    ParticipantOut,
    PersonOut,
    PersonWithCount,
    SpeakerStat,
    TagOut,
    TagWithCount,
)
from app.schemas.misc import (
    ChatAnswer,
    ChatMessageOut,
    ChatRequest,
    NotificationOut,
    SearchHit,
    SearchResponse,
    SearchResultMeeting,
    SoundbiteCreate,
    SoundbiteOut,
    StatsOut,
    UserOut,
    UserUpdate,
)
from app.schemas.summary import ChapterOut, SummaryOut, SummaryUpdate
from app.schemas.transcript import CommentCreate, CommentOut, SegmentOut, SegmentUpdate, SpeakerRef

__all__ = [
    "ActionItemCreate",
    "ActionItemOut",
    "ActionItemUpdate",
    "ActionItemWithMeeting",
    "ChapterOut",
    "ChatAnswer",
    "ChatMessageOut",
    "ChatRequest",
    "CommentCreate",
    "CommentOut",
    "MeetingCreate",
    "MeetingDetail",
    "MeetingListItem",
    "MeetingUpdate",
    "NotificationOut",
    "ORMModel",
    "Page",
    "ParticipantIn",
    "ParticipantOut",
    "PersonOut",
    "PersonWithCount",
    "SearchHit",
    "SearchResponse",
    "SearchResultMeeting",
    "SegmentOut",
    "SegmentUpdate",
    "SoundbiteCreate",
    "SoundbiteOut",
    "SpeakerRef",
    "SpeakerStat",
    "StatsOut",
    "SummaryOut",
    "SummaryUpdate",
    "TagOut",
    "TagWithCount",
    "UserOut",
    "UserUpdate",
]
